name: cyril-assessment

services:
  receipt-processor:
    image: receipt-processor:1.0.2
    container_name: receipt-processor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped